name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: compile
      run: g++ test.cpp performance.cpp -o test
    # uruchamianie programu every push
    #- name: run it
    #  run: ./test
